directories:
  profiles_directory: "/home/d/d_chante/d_chante/diviner_data/data/profiles"
  output_directory: "/home/d/d_chante/d_chante/diviner_data/data/output"

training_parameters:
  latent_variables: 4
  learning_rate: 1e-3
  patience: 2
  factor: 0.1
  beta: 0.2
  epochs: 50
  batch_size: 1000
  gpu: 0