directories:
  profiles_directory: "/esthar/diviner_data/data/profiles"
  output_directory: "/esthar/diviner_data/data/output"
  results_filepath: "/esthar/diviner_data/data/output/results.csv"

training_parameters:
  latent_variables: 4
  learning_rate: 1e-3
  gamma: 0.99
  beta: 0.2
  dropout: 0
  epochs: 200
  batch_size: 200
  gpu: 0