directories:
  profiles_directory: "/esthar/diviner_data/data/profiles"
  output_directory: "/esthar/diviner_data/data/output"

training_parameters:
  latent_variables: 4
  learning_rate: 1e-3
  patience: 5
  factor: 0.1
  beta: 0.2
  epochs: 50
  batch_size: 200
  gpu: 0