meta_config:
  description: "n/a"

data_config:
  input_data_path: "/workspace/datasets/profiles-v2/profiles-v2.csv"
  output_dir: "/workspace/outputs"

training_config:
  device: "cpu"
  latent_dim: 4
  batch_size: 200
  epochs: 100
  beta: 0.2
  learning_rate: 1e-3
  gamma: 0.1
  