directories:
  profiles_directory: "/speed_scratch/d_chante/diviner_data/data/profiles"
  output_directory: "/speed_scratch/d_chante/diviner_data/data/output"

training_parameters:
  latent_variables: 4
  learning_rate: 1e-3
  epochs: 50
  batch_size: 200
  n_splits: 5
  gpu: 0